version: "3.7"
services: 

    coreapp-react:
        image: "node:latest"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=development
        volumes:
        - /home/node/app/node_modules
        - ./coreapp-react:/home/node/app
        ports:
        - "8080:3000"
        command: "npm start"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.4.0

    coreapp-node:
        image: "node:latest"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=development
        volumes:
        - /home/node/app/node_modules
        - ./coreapp-node:/home/node/app
        ports:
        - "8081:5000"
        command: "npm start"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.4.1

    post-service:
        image: "node:latest"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=development
        volumes:
        - /home/node/app/node_modules
        - ./post-service:/home/node/app
        ports:
        - "8001:8081"
        command: "npm start"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.1.0

    comment-service:
        image: "node:latest"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=development
        volumes:
        - /home/node/app/node_modules
        - ./comment-service:/home/node/app
        ports:
        - "8002:8081"
        command: "npm start"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.2.0

    attribute-service:
        image: "node:latest"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=development
        volumes:
        - /home/node/app/node_modules
        - ./attribute-service:/home/node/app
        ports:
        - "8003:8081"
        command: "npm start"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.3.0

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - /data/db
        ports:
            - "8100:27017"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.5.0
            
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - "8004:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_SERVER: 10.10.5.0
        networks: 
            RateMyClass:
                ipv4_address: 10.10.6.0

    mysql-development:
        image: mysql:8.0.17
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASS: root
        volumes:
            - /var/lib/mysql
        ports:
            - "8200:3306"
        networks: 
            RateMyClass:
                ipv4_address: 10.10.7.0            

networks:
    RateMyClass:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16
