version: "3.7"
services:
    rabbitmq:
        image: 'bitnami/rabbitmq:3.8'
        env_file: .env
        ports:
            - '4369:4369'
            - '5672:5672'
            - '25672:25672'
            - '15672:15672'
        volumes:
            - /bitnami
        restart: always
        networks:
            RateMyClass:
                ipv4_address: "${RMQ_IP}"
    coreapp-react:
        image: "node:latest"
        working_dir: /home/node/app
        env_file: .env
        volumes:
        - /home/node/app/node_modules
        - ./coreapp-react:/home/node/app
        ports:
        - 8080:3000
        command: "npm start"
        restart: always
        networks: 
            RateMyClass:
                ipv4_address: "${coreapp_react_IP}"

    coreapp-node:
        image: "node:latest"
        working_dir: /home/node/app
        env_file: .env
        volumes:
        - /home/node/app/node_modules
        - ./coreapp-node:/home/node/app
        ports:
        - 8081:5000
        command: "npm start"
        restart: always
        networks: 
            RateMyClass:
                ipv4_address: "${coreapp_node_IP}"

    review-service:
        image: "node:latest"
        working_dir: /home/node/app
        env_file: .env
        volumes:
        - /home/node/app/node_modules
        - ./review-service:/home/node/app
        ports:
        - 8001:8081
        command: "npm start"
        restart: always
        networks: 
            RateMyClass:
                ipv4_address: ${post_service_IP}

    comment-service:
        image: "node:latest"
        working_dir: /home/node/app
        env_file: .env
        volumes:
        - /home/node/app/node_modules
        - ./comment-service:/home/node/app
        ports:
        - 8002:8081
        command: "npm start"
        restart: always
        networks: 
            RateMyClass:
                ipv4_address: "${comment_service_IP}"

    attribute-service:
        image: "node:latest"
        working_dir: /home/node/app
        env_file: .env
        volumes:
        - /home/node/app/node_modules
        - ./attribute-service:/home/node/app
        ports:
        - 8003:8081
        command: "npm start"
        restart: always
        networks: 
            RateMyClass:
                ipv4_address: "${attribute_service_IP}"

    mongo:
        image: mongo
        restart: always
        env_file: .env
        volumes:
            - /data/db
        ports:
            - 8100:27017
        networks: 
            RateMyClass:
                ipv4_address: "${MONGO_IP}"
            
    mongo-express:
        image: mongo-express
        env_file: .env
        restart: always
        ports:
            - 8004:8081
        networks: 
            RateMyClass:
                ipv4_address: "${MONGO_EXPRESS_IP}"

    mysql-development:
        image: mysql:8.0.17
        env_file: .env
        volumes:
            - /var/lib/mysql
        ports:
            - 8200:3306
        restart: always
        networks: 
            RateMyClass:
                ipv4_address: "${SQL_IP}"
networks:
    RateMyClass:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16
